### ISSUE TITLE
24 Hour clock

### ISSUE THREAD

**Issue by jay18001** [weilsonwonder/WWCalendarTimeSelector#1]
It would be nice to have a 24 hour clock option

**Comment by weilsonwonder** [comment]
@jay18001 do you have any ideas on how to make it integrate with a 24 hour UI? (:

**Comment by pmbfish40** [comment]
I have an idea see the screenshot

![screenshot_20170212-135306](https://cloud.githubusercontent.com/assets/5268958/22861132/b923515a-f12a-11e6-932a-14ad456cbe26.png)

**Comment by packia** [comment]
Hi, what is the API to show 24 hrs clock?

**Comment by tpid-rohmat** [comment]
Any update oh this issue?
