### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by Artimuss** [weilsonwonder/WWCalendarTimeSelector#11]
Hello guys!

Nice work.

How can I use the lib with my Swift 3 project ?
When I build, I have 365 issues with the lib due to the syntax difference between Swift 2 and Swift 3..

Regards

**Comment by weilsonwonder** [comment]
Ouch. This would require the author to fix up a Swift 3 version. (And that's me)

I'm still working on Swift 2 for now, hopefully I could find time to switch up to Swift 3 (:

As an alternative to this potentially long wait, you could fork the project and create a Swift 3 version (:
