### ISSUE TITLE
UIStoryboard exception after swift 3.0 update

### ISSUE THREAD

**Issue by Somojojojo** [weilsonwonder/WWCalendarTimeSelector#15]
Line 606 of WWCalendarTimeSelector.swift:
`let picker = UIStoryboard(name: "WWCalendarTimeSelector", bundle: bundle).instantiateInitialViewController() as! WWCalendarTimeSelector`

> 2016-09-15 14:33:28.329 ~~project name omitted~~[84835:4797498] Unknown class _TtC38WWCalendarTimeSelectorStoryboardBundle22WWCalendarTimeSelector in Interface Builder file.
Could not cast value of type 'UIViewController' (0x10db73dd8) to 'WWCalendarTimeSelector.WWCalendarTimeSelector' (0x10e2b1028).

I've refactored my code to instantiate each time the selector is needed, and this error still comes up.

Can anybody else reproduce this? It happens when calling `WWCalendarTimeSelector.instantiate()`

**Comment by Somojojojo** [comment]
Is there a specific reason the ViewController is instantiated via `instantiateInitialViewController` instead of `instantiateViewController(withIdentifier: "")`? The later is safer. Just give the ViewController a storyboard ID and instantiate with the identifier.

**Comment by weilsonwonder** [comment]
Hi, you can goto the storyboard and remove the modules from the uiviewcontrollers and one of the custom uiview. It should fix the errors. I'm having issues pushing onto cocoapods to update my library as well lol

apologies for the issues!

**Comment by Somojojojo** [comment]
Hmm, actually _adding_ `WWCalendarTimeSelector` as the module for the main UIViewController and the WWClock UIView fixed the issue completely. Thanks for your help, @weilsonwonder :) Are you going to put that change into your repo, or do you want a PR?

**Comment by lifehappensoutdoors** [comment]
Hello, the issue described above seems to be unresolved. Any special branch we need to pull from?
If we remove the custom class from the storyboard file it crashes with the unknown class error. If we add the classes, it works fine but the protocol methods won't work, date selection for example. 
Any input from your side is highly appreciated...

Nice component by the way. Thank you for sharing.
