### ISSUE TITLE
feature request: select a date range

### ISSUE THREAD

**Issue by mave99a** [weilsonwonder/WWCalendarTimeSelector#2]
feature request: select a date range.  Allow to select a start date and an end date.

**Comment by girishnair12345** [comment]
Also a minimum date range would be nice, so that user is not allowed to select beyond that date

**Comment by weilsonwonder** [comment]
@mave99a sure I will add date range option (:

@girishnair12345 I actually allow a finer grain of controls for whether the user is allowed or not to select date. Take a look at the protocol method `func WWCalendarTimeSelectorShouldSelectDate(selector: WWCalendarTimeSelector, date: NSDate) -> Bool`

**Comment by weilsonwonder** [comment]
@mave99a I have updated the library with a new date range option. Will update the realm in time to come, thanks for using my library! Cheers~

**Comment by RnyG** [comment]
@weilsonwonder hey man, i think your library is awesome, i'm using the swift 2.3 version (i think so) But i don't figure out how use "WWCalendarTimeSelectorShouldSelectDate(selector: WWCalendarTimeSelector, date: NSDate) -> Bool" to disable past dates, i need to set user able to select dates next 3 days from today, and in clock view, select hour in 8am- 8pm. How i can do that? Thanks!
