### ISSUE TITLE
'Could not find a storyboard named 'WWCalendarTimeSelector' in bundle NSBundle

### ISSUE THREAD

**Issue by marian19** [weilsonwonder/WWCalendarTimeSelector#21]
let picker = UIStoryboard(name: "WWCalendarTimeSelector", bundle: bundle).instantiateInitialViewController() as! WWCalendarTimeSelector

Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Could not find a storyboard named 'WWCalendarTimeSelector' in bundle NSBundle

**Comment by diego-watanabe** [comment]
I have this same issue.

**Comment by marian19** [comment]
I fixed by set the module for the view controller in WWCalendarTimeSelector.storyboard and set the module for the clock view

**Comment by sarath435** [comment]
could not found a storyboard name WWCalendarTimeSelector.storyboard.how can i find solution....

**Comment by sarath435** [comment]
reason: 'Could not find a storyboard named 'WWCalendarTimeSelector' in bundle NSBundle

even though setting view controller name and clock view module names ...its not working and getting same error... can anyone solved this??

**Comment by Jbr99921** [comment]
I'm using DemoBaseViewController in place of UIViewController to show chart in main Storyboard file and also need to use date for date ranger in that screen so i also use pod file pod 
 'WWCalendarTimeSelector' with that having  WWCalendarTimeSelector.storyboard file and i'm facing issue is :   Unknown class _TtC10Budget_NVT22WWCalendarTimeSelector in Interface Builder file.
Could not cast value of type 'UIViewController' (0x1072001f0) to 'WWCalendarTimeSelector.WWCalendarTimeSelector' (0x107f03ce0).
2019-05-03 18:46:23.015841+0530 Budget[18071:321127] Could not cast value of type 'UIViewController' (0x1072001f0) to 'WWCalendarTimeSelector.WWCalendarTimeSelector' (0x107f03ce0).

**Comment by ralspatel** [comment]
I have the same issue

'Could not find a storyboard named 'WWCalendarTimeSelector' in bundle NSBundle'

can anyone help me to solve this problem, I integrate this library with pod.

thanks
