### ISSUE TITLE
Selected date/time always four hours ahead

### ISSUE THREAD

**Issue by akmalshukri** [weilsonwonder/WWCalendarTimeSelector#54]
func WWCalendarTimeSelectorDone(_ selector: WWCalendarTimeSelector, date: NSDate) {
        print("Selected \n\(date)\n---")
        singleDate = date as Date
    }

or

func WWCalendarTimeSelectorDone(_ selector: WWCalendarTimeSelector, date: Date) {
        print("Selected \n\(date)\n---")
        singleDate = date
    }

got the same issue .. How to solve this issue  ?

**Comment by nizzam** [comment]
Have you fixed this issue @akmalshukri ?

**Comment by akmalshukri** [comment]
@nizzam Yes, already solve the issue ..

**Comment by nizzam** [comment]
@akmalshukri do you mind to share your solutions ?

**Comment by akmalshukri** [comment]
I just play with trick .. You put this one in that func

let calendar = NSCalendar.autoupdatingCurrent
singleDate = calendar.date(byAdding:.hour, value: -4, to: date as Date)!
print("Selected \n\(singleDate)\n---")

It will reduce 4 hours ..
