### ISSUE TITLE
Time value changed after switching AM and PM

### ISSUE THREAD

**Issue by sgermain06** [weilsonwonder/WWCalendarTimeSelector#59]
For some reason, if I present a time selector, I can select an hour and then change from AM to PM. After changing AM/PM, the value of the hour I selected changes. Is it possible to retain the selected hour value when changing AM/PM?

**Comment by sgermain06** [comment]
I found the problem. The problem is that the `touchesMoved:` method was being called every time the view was touched, regardless of where, calling `touchClock:`. That method is selecting a time based on an angle calculation from the center of the view. Touching AM/PM was triggering that method, calculating that AM meant 7 o'clock was selected, same as PM, selecting 5 o'clock.

I added a check to the `touchesMoved:` method to see if the touch is within the bounds for the AM and PM buttons and if not, call `touchClock:`. Now the selected time remains.

**Comment by EngSojoud90** [comment]
> I found the problem. The problem is that the `touchesMoved:` method was being called every time the view was touched, regardless of where, calling `touchClock:`. That method is selecting a time based on an angle calculation from the center of the view. Touching AM/PM was triggering that method, calculating that AM meant 7 o'clock was selected, same as PM, selecting 5 o'clock.
> 
> I added a check to the `touchesMoved:` method to see if the touch is within the bounds for the AM and PM buttons and if not, call `touchClock:`. Now the selected time remains.

please can you provide me clear solution
