### ISSUE TITLE
Selected time is always four hours ahead

### ISSUE THREAD

**Issue by lancevalour** [weilsonwonder/WWCalendarTimeSelector#6]
Hi,

So I always get the wrong time after I click the Done button. 

```swift 
func WWCalendarTimeSelectorDone(selector: WWCalendarTimeSelector, date: NSDate) {
        print(date)
 }
```

Printed out time is always four hours ahead. I'm not sure what is going on here...

Thanks,
Yicheng

**Comment by dev4dev** [comment]
try to use DateFormatter for printing date string, sometimes console could print date in wrong timeZone or something like that

**Comment by lancevalour** [comment]
Thank you for your help. I think this can be closed.

**Comment by commando24** [comment]
Actually console always print date in UTC. may be thats why date is not printed as expected.

**Comment by akmalshukri** [comment]
how to solve it ? i also got the same issue .. not correct time when selected ..
